title: Ziqiang Chen
url: "https://ziqiangc.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "0.jpg"

tracking_id: #

#footer: yes
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://ziqiangc.github.io"
 - name: "Resume"
   link: "main.pdf"
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"